### ISSUE TITLE
Big uploads will fail

### ISSUE THREAD

**Issue by valenting** [edgul/logup#1] opened 2024-05-21 13:12 UTC
I found the cause to be this dependency https://github.com/axios/axios/issues/5662

I think for uploading new files we could be using the HTTP req directly https://developers.google.com/drive/api/guides/manage-uploads#http_2

**Comment by edgul** [comment] 2024-05-21 13:33
axios dependency should have been removed a few days ago. Did you test with the latest?

**Comment by valenting** [comment] 2024-05-21 13:35
It seems the google nodejs library still uses it.

**Comment by edgul** [comment] 2024-05-21 13:40
Ah, thanks

**Comment by edgul** [comment] 2024-07-11 20:29
Tried to switch to node https for file upload, no luck yet: https://github.com/edgul/logup/compare/main...fix-big-file-failure 
Works for 1GB, fails for 3GB

**Comment by edgul** [comment] 2024-07-22 15:29
Note that 3GB manual upload with browser to the target server doesn't fail, so it doesn't seem to be a target-server config issue.

**Comment by edgul** [comment] 2024-07-25 15:42
I was able to upload a 3GB file by directly passing `const readStream = fs.createReadStream(filename);` to `drive.files.create`. So I think the issue is with multer.

**Comment by edgul** [comment] 2024-07-25 19:17
Should be fixed with https://github.com/edgul/logup/commit/c43c8fd1ff6605314342243dee92441e461cd6e8

**Closed as completed by edgul** 2024-07-25 19:17 UTC
